MCU_LDSCRIPT = SN32F260

####LDFLAGS += --specs=nano.specs
USE_LINK_GC = yes
LTO_ENABLE = yes

EXTRAFLAGS += -flto

USE_EXCEPTIONS_STACKSIZE = 0xD0
USE_PROCESS_STACKSIZE = 0x1E0

# process stack size of 0x1c0 crashes during SEND_STRING
USE_EXCEPTIONS_STACKSIZE = 0xD0
# # 0x180 140 f0 d0    80gg a0gg b0gg b8gg c0 ok
USE_PROCESS_STACKSIZE = 0x1E0
