#pragma once

// #define NO_ACTION_MACRO
// #define NO_ACTION_FUNCTION

#define NO_DEBUG 1
#define NO_PRINT 1

#define LAYER_STATE_8BIT


// #undef LOCKING_SUPPORT_ENABLE
// #undef LOCKING_RESYNC_ENABLE

#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING

#define USB_DEFAULT_BUFFER_CAPACITY 1
