#pragma once

// #define NO_ACTION_MACRO
// #define NO_ACTION_FUNCTION

#define NO_DEBUG 1
#define NO_PRINT 1

#define LAYER_STATE_8BIT


// #undef LOCKING_SUPPORT_ENABLE
// #undef LOCKING_RESYNC_ENABLE

//#define SN32F2XX_PWM_CONTROL SOFTWARE_PWM
//#define SN32F2XX_RGB_MATRIX_ROWS_HW (SN32F2XX_RGB_MATRIX_ROWS * SN32F2XX_RGB_MATRIX_ROW_CHANNELS)

#define NO_ACTION_ONESHOT
#define NO_ACTION_TAPPING

#define USB_DEFAULT_BUFFER_CAPACITY 1

#define SN32F2XX_PWM_OUTPUT_ACTIVE_LEVEL SN32F2XX_PWM_OUTPUT_ACTIVE_HIGH
#define SN32F2XX_RGB_OUTPUT_ACTIVE_LEVEL SN32F2XX_RGB_OUTPUT_ACTIVE_LOW


//#define SHARED_MATRIX
//
//#define SN32F2XX_PWM_DIRECTION COL2ROW
//// #define SN32F2XX_RGB_MATRIX_ROW_PINS { C2, A2, C10, C7, C4, D6, C0, A0, A3, C9, C6, C3, C1, A1, A4, C8, C5, D7 }  //RGB order
//// #define SN32F2XX_RGB_MATRIX_ROW_PINS { C2, C0, C1, A2, A0, A1, C10, A3, A4, C7, C9, C8, C4, C6, C5, D6, C3, D7 }  //RGB order
//#define SN32F2XX_RGB_MATRIX_ROW_PINS { C2, C0, C1, C7, C9, C8 }  //RGB orders
//
//// #define SN32F2XX_RGB_MATRIX_COL_PINS MATRIX_COL_PINS
//#define SN32F2XX_RGB_MATRIX_COL_PINS { A7, A8, A9 }
//
//#define RGB_MATRIX_LED_COUNT (6)
//
//#define SN32F2XX_ACTIVATE_PWM_CHAN_5 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_6 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_7 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_8 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_9 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_10 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_11 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_12 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_13 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_14 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_15 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_16 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_17 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_18 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_19 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_20 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_21 //
//#define SN32F2XX_ACTIVATE_PWM_CHAN_22 //